name: rorigami
description: Rorigami - Static pages made simple.
# version: 1.0.0
#homepage: http://rorigami.site

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  markdown: ^2.1.3
  yaml: ^2.2.0
  logging: ^0.11.4

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
